SistemaBase/Controllers/Operaciones/MatrizGestionController.cs
using DAO.Base;
using DevExpress.Web.Mvc;
using ENTIDADES.Base;
using ENTIDADES.Login;
using ENTIDADES.Mantenimiento;
using ENTIDADES.Operaciones;
using SERVICIO.Login;
using SERVICIO.Mantenimiento;
using SERVICIO.Operaciones;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SistemaBase.Controllers.Operaciones
{
    public class MatrizGestionController : Controller
    {
        SERVICIO.Operaciones.MatrizGestionServicio MatrizGestionService = new SERVICIO.Operaciones.MatrizGestionServicio();
        SERVICIO.Mantenimiento.OperacionesServicio OperacionService = new SERVICIO.Mantenimiento.OperacionesServicio();
        UsuarioViewModel usuarioResponse = new UsuarioViewModel();
        LoginServicio LoginSer = new LoginServicio();

        // GET: MatrizGestion
        //public ActionResult Index()
        //{
        //    return View();
        //}

        public ActionResult MatrizGestion()
        {
            return View();
        }

        //Listado de las sucursales
        [HttpPost]
        public JsonResult Sucursal()
        {
            List<MatrizGestionViewModel> listaMatrizGestion = null;
            List<SelectListItem> Lista = new List<SelectListItem>();
            try
            {
                int valorLista = (int)MatrizGestionServicio.ListaMatrizGestion.Lista_Suc;
                listaMatrizGestion = MatrizGestionService.ListarSucursalServicio(valorLista);
                foreach (var val in listaMatrizGestion)
                {
                    Lista.Add(new SelectListItem { Text = Convert.ToString(val.NomSuc), Value = Convert.ToString(val.CveSuc) });
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return Json(new SelectList(Lista, "Value", "Text", JsonRequestBehavior.AllowGet));
        }

        //Crear conexion con las sucursales
        public JsonResult Conexion(MatrizGestionViewModel matrizGestion)
        {
            ConexionSucursalViewModel cadenaConexion = null;
            cadenaConexion = new ConexionSucursalViewModel();
            MatrizGestionViewModel metaCartera = new MatrizGestionViewModel();
            int totalResgistros = 0;

            // cadena de conexion del web config (cadenaConexion);
            string[] valores = System.Web.Configuration.WebConfigurationManager.AppSettings[matrizGestion.CveSuc.Trim()].Split(':');
            //crear cadena de conexion
            cadenaConexion.cadena = "Data Source =" + valores[0] + "\\sqlserver;Initial Catalog=Empeño; Persist Security Info=True; Uid=sa;Pwd=" + valores[1] + "";
            //agregarlo a una session
            cadenaConexion.sucursal = valores[2];

            System.Web.HttpContext.Current.Session["conexionDB"] = cadenaConexion;

            //validar si se encontro en el web config
            if (valores.Equals(""))
            {
                return Json("0.0.0.0: No se encontro conexion");
                //cadenaConexion.cadena = "0.0.0.0: No se encontro conexion";
            }
            else
            {
                //validar si se realizo la conexion
                if (VerifyConnection(cadenaConexion) == true)
                {
                    int valor = (int)MatrizGestionServicio.ConsultaMatrizGestion.Con_MetaCartera;
                    //consultar la meta de cartera (REAL)
                    metaCartera = MatrizGestionService.ConsultaMetaCartera(valor, cadenaConexion);

                    //consultar la meta de ingreso (REAL)
                    valor = (int)MatrizGestionServicio.ConsultaMatrizGestion.Con_MetaIngreso;
                    MatrizGestionViewModel metaIngreso = new MatrizGestionViewModel();
                    //consultar la meta de ingreso (REAL)
                    metaIngreso = MatrizGestionService.ConsultaMetaIngreso(valor, cadenaConexion);
                    metaCartera.ingreso = metaIngreso.ingreso;

                    //cosulta clientes nuevos empeños (REAL)
                    valor = (int)MatrizGestionServicio.ConsultaMatrizGestion.Con_ClienteNvo;
                    MatrizGestionViewModel CltNvo = new MatrizGestionViewModel();
                    CltNvo = MatrizGestionService.ConsultaCteNvo(valor, cadenaConexion);
                    metaCartera.TotalCteNvo = CltNvo.TotalCteNvo;
                    metaCartera.NumClientes = CltNvo.NumClientes;

                    //cosulta clientes nuevos ventas(REAL)
                    valor = (int)MatrizGestionServicio.ConsultaMatrizGestion.Con_ClienteNvoVta;
                    MatrizGestionViewModel CltNvoVta = new MatrizGestionViewModel();
                    CltNvoVta = MatrizGestionService.ConsultaCteNvoVta(valor, cadenaConexion);
                    metaCartera.NumClientesVta = CltNvoVta.NumClientesVta;

                    //cosulta promedio monto empeño (REAL)
                    valor = (int)MatrizGestionServicio.ConsultaMatrizGestion.Con_PromMontoEmp;
                    MatrizGestionViewModel PromMontoEmp = new MatrizGestionViewModel();
                    PromMontoEmp = MatrizGestionService.ConsultaPromedioMontoEmpeño(valor, cadenaConexion);
                    metaCartera.PromedioSem = PromMontoEmp.PromedioSem;
                    metaCartera.FolioCapPrest = PromMontoEmp.FolioCapPrest;


                    //cosulta promedio monto empeño (REAL)
                    valor = (int)MatrizGestionServicio.ConsultaMatrizGestion.Con_PorcMaxEna;
                    MatrizGestionViewModel PorcMaxEna = new MatrizGestionViewModel();
                    PorcMaxEna = MatrizGestionService.ConsultaPorcMaxEna(valor, cadenaConexion);
                    metaCartera.Folios = PorcMaxEna.Folios;


                    //cosulta promedio monto empeño (REAL)
                    valor = (int)MatrizGestionServicio.ListaMatrizGestion.Lista_IngresoVta;
                    MatrizGestionViewModel IngreVta = new MatrizGestionViewModel();
                    IngreVta = MatrizGestionService.ListarIngresoVtaServicio(valor, cadenaConexion);
                    metaCartera.IngresoVenta = IngreVta.IngresoVenta;
                    //metaCartera.


                    //cosulta ingreso total (REAL)
                    valor = (int)MatrizGestionServicio.ConsultaMatrizGestion.Con_IngTotal;
                    MatrizGestionViewModel IngreTotal = new MatrizGestionViewModel();
                    IngreTotal = MatrizGestionService.ConsultaIngTotal(valor, cadenaConexion);
                    metaCartera.IngTotal = IngreTotal.IngTotal;

                    //cosulta cartera apartado, celular y joyeria (REAL)
                    valor = (int)MatrizGestionServicio.ListaMatrizGestion.Lista_Cartera;
                    MatrizGestionViewModel Cartera = new MatrizGestionViewModel();
                    Cartera = MatrizGestionService.ListarCarteraServicio(valor, cadenaConexion);
                    metaCartera.CarteraView = Cartera.CarteraView;

                    //Cartera total 
                    valor = (int)MatrizGestionServicio.ConsultaMatrizGestion.Con_CarTotal;
                    MatrizGestionViewModel CarteraTotal = new MatrizGestionViewModel();
                    CarteraTotal = MatrizGestionService.ConsultaCartTotal(cadenaConexion, valor);
                    metaCartera.CarteraTotal = CarteraTotal.CarteraTotal;

                    //Guardar datos en la bitacora acceso

                    MensajeTransaccion mensaje = new MensajeTransaccion();
                    usuarioResponse = (UsuarioViewModel)Session["usuario"];
                    usuarioResponse.CveSucursal = valores[3];


                    using (var conn = new SqlConnection(BaseDAO.analiticabd))
                    {
                        string query = "select count(BitacoraID) as totalResgistros  from BITACORAACCESO where Usuario ='" + usuarioResponse.CodigoAlterno + "' and "
                             + "SucursalID ='" + valores[3].Trim() + "' and YEAR(Fecha) = YEAR(GETDATE()) and month(Fecha) = month(GETDATE()) and DAY(Fecha) = DAY(GETDATE())";
                        SqlCommand cmds = new SqlCommand(query, conn);
                        conn.Open();
                        SqlDataReader reader = cmds.ExecuteReader();
                        if (reader.Read())
                        {
                            totalResgistros = int.Parse(reader["totalResgistros"].ToString().Trim());
                        }
                        reader.Close();
                    }

                    if (totalResgistros < 1)
                    {
                        mensaje = LoginSer.AltaBitacoraAcceso(usuarioResponse);
                    }

                    return Json(metaCartera);
                }
                else
                {
                    return Json("Error al conectar, intentar mas tarde.");
                }


            }
            // return cadenaConexion;
            // return Json("");
        }

        public bool VerifyConnection(ConexionSucursalViewModel cadenaConexion)
        {

            string connetionString = null;
            SqlConnection cnn;
            connetionString = cadenaConexion.cadena.ToString();

            cnn = new SqlConnection(connetionString);
            try
            {
                cnn.Open();
                cnn.Close();
                return true;
            }
            catch
            {
                return false;
            }

        }

        public JsonResult Base(OperacionesViewModel operaciones)
        {
            List<OperacionesViewModel> lista = null;
            try
            {
                int valorLista = (int)OperacionesServicio.Lista.Lista_BaseSuc;
                lista = OperacionService.ListarBaseServicio(operaciones, valorLista);
            }
            catch (Exception)
            {

                throw;
            }

SistemaBase/Controllers/Operaciones/MatrizGestionGraficaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SistemaBase.Controllers.Operaciones
{
    public class MatrizGestionGraficaController : Controller
    {
        // GET: MatrizGestionGrafica
        public ActionResult Index()
        {
            return View();
        }
    }
}

SistemaBase/Views/Operaciones/OpcionesBase.cshtml
@model ENTIDADES.Mantenimiento.OperacionesViewModel
@{
    ViewBag.Title = "Actualizar producto";
    Layout = null;
}

<script src="~/Scripts/js/bootstrap.js"></script>

<form id="FormBase">
    <h4 class="Indicacion">Folio:</h4>
    <input class="resultado" type="text" id="BaseID" name="BaseIDs" value="@Model.BaseID" readonly />

    <h4 class="Indicacion">Nombre:</h4>
    @Html.DropDownListFor(m => m.Nombre, (SelectList)ViewBag.NombreBase, new { @class = "lista" })

    <h4 class="Indicacion">Meta:</h4>
    <input class="resultado" type="text" id="Valor" name="Valors" value="@Model.Valor" maxlength="100" autocomplete="off">

    <div class="boxes" style="padding:15px 40px 15px; text-align: left!important;">
        <input type="checkbox" id="ChangeS">
        <label for="ChangeS">Cambiar sucursal</label>
    </div>

    <h4 class="Indicacion">Sucursal:</h4>
    @*@Html.DropDownList("SucursalIDEdit", ViewBag.Sucursal as List<SelectListItem>, new { @class = "lista", @name = "SucursalID" })*@
    <input class="resultado" type="text" id="SucursalIDtxt" name="SucursalID" value="@Model.SucursalID" maxlength="100" autocomplete="off" readonly>
    @Html.DropDownList("SucursalIDMod", new SelectList(string.Empty, "Value", "Text"), "- Sucursal -", new { @class = "lista resultado val", @name = "SucursalIDM"})


    <h4 class="Indicacion">Aliado:</h4>
    @*@Html.DropDownList("AliadoID", ViewBag.Aliado as List<SelectListItem>, new { @class = "lista", @name = "AliadoID" })*@
    <input class="resultado" type="text" id="AliadoIDtxt" name="AliadoID" value="@Model.AliadoID" maxlength="100" autocomplete="off" readonly>
    @Html.DropDownList("AliadoIDMod", new SelectList(string.Empty, "Value", "Text"), "- Aliado -", new { @class = "lista resultado val", @name = "AliadoIDM"})


    <h4 class="Indicacion">Mes:</h4>
    <input class="Indicacion" type="month" id="NomMes" name="NomMes" value="@Model.NomMes" >

    <div class="modal-footer">
        <button class="cnc" onclick="location.reload();" type="button" data-dismiss="modal" aria-label="Close" style="padding:4px 10px 2px!important;" >Cancelar</button>
        <button type="button" class="ok" onclick="Modificar()">Guardar</button>
    </div>
</form>
<style>
    .val{
        display:none;
    }
</style>
<script>
    //cambio de la sucursal para filtrar aliado
    //AL CAMBIAR SUCURSAL SE FILTRAN LOS ALIADOS, SE CARGA LA SUCURSAL Y CUANDO SE CAMBIE LA SUCURSAL SE CARGAN LOS ALIADOS

    //Elegir cambio de sucursal
    $("#ChangeS").change(function () {

        $("#SucursalIDMod").removeClass('val');
        $("#AliadoIDMod").removeClass('val');

        $("#SucursalIDtxt").addClass('val');
        $("#AliadoIDtxt").addClass('val');

        //SUCURSAL
        $.ajax({
            //url: "../MatrizGestion/Sucursal",
            url: '@Url.Action("Sucursal", "MatrizGestion")',
            type: "POST",
            dataType: 'json',
            contentType: "application/json; charset=utf-8",
            success: function (SucursalModificar) {
                console.log(SucursalModificar);
                $.each(SucursalModificar, function (i, SucursalModificar) {
                    $("#SucursalIDMod").append('<option value="' + SucursalModificar.Value + '">' + SucursalModificar.Text + '</option>');
                });
            },
        });

    });

    //Aal cambiar la sucursal/Elegir sucursal cambiar o desplegar los aliados
    $("#SucursalIDMod").change(function () {
        
        var combo = document.getElementById("SucursalIDMod");
        var NomSuc = combo.options[combo.selectedIndex].text;
        var CveSuc = combo.options[combo.selectedIndex].value;
       
        $.ajax({
            url: '@Url.Action("Aliado", "MatrizGestion")',
            type: 'POST',
            dataType: 'json',
            data: { NomSuc, CveSuc},
            success: function (AliadoModificar) {
                console.log(AliadoModificar);
                $.each(AliadoModificar, function (i, AliadoModificar) {
                    $("#AliadoIDMod").append('<option value="' + AliadoModificar.Value + '">' + AliadoModificar.Text + '</option>');
                });

            },
        })
    });

</script>

@*Mensaje al modificar la base*@
<div class="modal fade" id="mensajeActModal" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                @*<h4 class="modal-title" id="staticBackdropLabel">Alta de base</h4>*@
            </div>
            <div class="modal-body">
                <div id="resultadoMod" class="text-center"></div>
                <button class="cnc" onclick="location.reload();" type="button">
                    Cerrar.
                </button>
            </div>

        </div>
    </div>
</div>

@* MODIFICAR LA META *@
<script type="text/javascript">
    function Modificar() {

        var BaseID = $("#BaseID").val();
        Nombre = document.getElementsByName("Nombre")[1].value;
        Valor = document.getElementById("Valor").value;
        mesAnio = $("#NomMes").val();

        if (ChangeS.checked == true) {
            //CARGAR LOS VALORES DEL COMBOBOX
            var combo = document.getElementById("SucursalIDMod");
            var SucursalID = combo.options[combo.selectedIndex].text;   
            AliadoID = $("#AliadoIDMod").val();
        }
        else {
            //BUSCAR LOS VALORES DEL TEXTBOX
            SucursalID = $("#SucursalIDtxt").val();
            AliadoID = $("#AliadoIDtxt").val();
        }

        if (BaseID.length == 0 || Nombre.length == 0 || Valor.length == 0 || SucursalID.length == 0 || AliadoID.length == 0 || mesAnio.length == 0) {
           // validar();
        }
        else {
            $.ajax({
                type: 'POST',
                url: '@Url.Action("ActualizarBase")',
                dataType: 'json',
                data: { BaseID, Nombre, Valor, SucursalID, AliadoID, mesAnio },
                success: function (MensajeRespuesta) {                   

                    $("#mensajeActModal").modal("show");
                   $('#resultadoMod').html(MensajeRespuesta);

                },
            });

        }

    }

</script>


<script type="text/javascript">
    function validar() {
        jQuery.validator.setDefaults({

        });
        $("#FormBase").validate({
            ignore: [],

            rules: {
                BaseID: {
                    required: true
                },
                Nombre: {
                    required: true
                },
                Valor: {
                    required: true
                },
                SucursalID: {
                    required: true
                },
                AliadoID: {
                    required: true
                },
                mesAnio: {
                    required: true
                }
            },
            messages: {
                BaseID: {
                    required: "Se require el folio de la base"
                },
                Nombre: {
                    required: "Se require el nombre de la base"
                },
                Valor: {
                    required: "Se requiere el valor de la base"

                },
                SucursalID: {
                    required: "Se requiere la sucursal de la base"
                },
                AliadoID: {
                    required: "Se requiere el aliado de la base"
                },
                mesAnio: {
                    required: "Se requiere la fecha de la base"
                }

            }
        });
   }
</script>

SistemaBase/Views/Operaciones/OpcionesDiaHabil.cshtml
@model ENTIDADES.Mantenimiento.OperacionesViewModel
@{
    ViewBag.Title = "Actualizar dia habil";
    Layout = null;
}


@*<script src="~/Scripts/jquery-2.2.3.js"></script>*@

<form id="FormBase">
    
    <h4 class="Indicacion">Sucursal:</h4>
    @Html.DropDownList("SucursalID", ViewBag.Sucursal as List<SelectListItem>, new { @class = "lista", @name = "SucursalID" })

    <h4 class="Indicacion">Mes:</h4>
    <input class="Indicacion" type="month" id="mesAnio" name="mesAnio" value="@Model.mesAnio">


    <h4 class="Indicacion">Cantidad:</h4>
    @*<input class="resultado" type="text" id="Cantidad" name="Cantidad" value="@Model.Cantidad" maxlength="100" autocomplete="off">*@
    <input type="text" class="Indicacion date" name="FechaInhabil" id="FechaInhabil">

    
    <div class="modal-footer">
        <button class="cnc" type="button" data-dismiss="modal" aria-label="Close" style="padding:4px 10px 2px!important;">Cancelar</button>
        <button type="button" class="ok" onclick="Modificar()">Guardar</button>
    </div>
</form>

<script>
    //INICIAR CALENDARIO
    $(".date").datepicker({
        multidate: true,
        format: "dd-mm-yyyy",
        'language': 'es'
    });
</script>

@*Mensaje al modificar la base*@
<div class="modal fade" id="mensajeActModal" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
            </div>
            <div class="modal-body">
                <div id="resultadoMod" class="text-center"></div>
                <button class="cnc" onclick="location.reload();" type="button">
                    Cerrar.
                </button>
            </div>

        </div>
    </div>
</div>


<script type="text/javascript">
    function Modificar() {

        var Folio = $("#Folio").val();
        var SucursalID = document.getElementsByName("SucursalID")[1].value;
        var mesAnio = document.getElementsByName("mesAnio")[1].value;
        var Cantidad = document.getElementsByName("Cantidad")[1].value;

        if (Folio.length == 0 || SucursalID.length == 0 || mesAnio.length == 0 || Cantidad.length == 0) {
           // validar();
        }
        else {
            $.ajax({
                type: 'POST',
                url: '@Url.Action("ActualizarDiaHabil")',
                dataType: 'json',
                data: { Folio, SucursalID, mesAnio, Cantidad },
                success: function (MensajeRespuesta) {

                    $('#DivBase').modal('hide');
                    $('#mensajeActModal').modal('show');
                    $('#resultadoMod').html(MensajeRespuesta);

                },
            });

        }

    }
</script>


@*<script type="text/javascript">
        function validar() {
            jQuery.validator.setDefaults({

            });
            $("#FormBase").validate({
                ignore: [],

                rules: {
                    BaseID: {
                        required: true
                    },
                    Nombre: {
                        required: true
                    },
                    Valor: {
                        required: true
                    },
                    SucursalID: {
                        required: true
                    },
                    AliadoID: {
                        required: true
                    },
                    mesAnio: {
                        required: true
                    }
                },
                messages: {
                    BaseID: {
                        required: "Se require el folio de la base"
                    },
                    Nombre: {
                        required: "Se require el nombre de la base"
                    },
                    Valor: {
                        required: "Se requiere el valor de la base"

                    },
                    SucursalID: {
                        required: "Se requiere la sucursal de la base"
                    },
                    AliadoID: {
                        required: "Se requiere el aliado de la base"
                    },
                    mesAnio: {
                        required: "Se requiere la fecha de la base"
                    }

                }
            });
       }
    </script>*@

SistemaBase/Views/Operaciones/Prueba.cshtml
@{
    ViewBag.Title = "ManDiaHabil";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.2/css/bootstrap-select.min.css" rel="stylesheet" />
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.2/js/bootstrap-select.min.js"></script>

<select class="selectpicker" multiple name="combobox" id="combobox">
    @*<option value="1">UNO</option>
    <option value="2">DOS</option>
    <option value="3">TRES</option>
    <option value="4">CUATRO</option>*@
</select>
<br />
<button onclick="verValor()">Prueba</button>
<script>
  function verValor() {
    var valores = $.map(
      $('#combobox option:selected'),
      function(o, i) { return $(o).text(); });
    alert(valores.join(', '));
  }
</script>


<script>
    $(document).ready(function () {



        $.ajax({
            type: 'POST',
            url: '@Url.Action("Sucursal", "MatrizGestion")',
            dataType: 'json',
            success: function (Sucursal) {


                $.each(Sucursal, function (i, Sucursal) {
                    $("#combobox").append('<option value="' + Sucursal.Value + '">' + Sucursal.Text + '</option>');
                });
            }
        })


    });
  
</script>