SistemaBase/Controllers/Mantenimiento/OperacionesController.cs
using DevExpress.Web.Mvc;
using ENTIDADES.Base;
using ENTIDADES.Mantenimiento;
using ENTIDADES.Operaciones;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using SERVICIO.Mantenimiento;
using SERVICIO.Operaciones;
using SistemaBase.Controllers.Operaciones;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using static ENTIDADES.Mantenimiento.OperacionesViewModel;

namespace SistemaBase.Controllers.Mantenimiento
{
    public class OperacionesController : Controller
    {

        SERVICIO.Mantenimiento.OperacionesServicio OperacionService = new SERVICIO.Mantenimiento.OperacionesServicio();
        SERVICIO.Operaciones.PromedioPrestamoServicio PromedioPService = new SERVICIO.Operaciones.PromedioPrestamoServicio();

        SERVICIO.Operaciones.MatrizGestionServicio MatrizGestionService = new SERVICIO.Operaciones.MatrizGestionServicio();
        

        // GET: Operaciones
        public ActionResult Index()
        {
            return View();
        }

        //catalogo manteniemiento para la base de matriz de gestion.
        public ActionResult MantMatrizGestion(OperacionesViewModel operaciones)
        {
            List<OperacionesViewModel> lista = null;
            try
            {
                int valorLista = (int)OperacionesServicio.Lista.Lista_BaseAll;
                lista = OperacionService.ListarBaseServicio(operaciones,valorLista);
            }
            catch (Exception)
            {
                throw;
            }
            return View(lista);
        }

        public JsonResult Sucursal()
        {
            List<PromedioPrestamoViewModel> listaPromedioPrestamo = null;
            List<SelectListItem> Lista = new List<SelectListItem>();
            try
            {
                int valorLista = (int)PromedioPrestamoServicio.ListaPromedioPrestamo.List_Suc;
                listaPromedioPrestamo = PromedioPService.ListarNomSucServicio(valorLista);
                foreach (var val in listaPromedioPrestamo)
                {
                    Lista.Add(new SelectListItem { Text = Convert.ToString(val.NomSuc), Value = Convert.ToString(val.NomSuc) });
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
            ViewBag.Sucursal = Lista;
            return Json(new SelectList(Lista, "Value", "Text", JsonRequestBehavior.AllowGet));
        }
        [HttpPost]
        //Alta de nueva base de la matriz de gestion en el catalogo de operaciones.
        public JsonResult AltaMatrizGestionBase(OperacionesViewModel MatrizGestion)
        {

            MensajeTransaccion mensaje = null;

            try
            {
                //mensaje = ProductoSer.AltaProductoServicio(producto, usuarioResponse);
                mensaje = OperacionService.AltaProductoServicio(MatrizGestion);
            }
            catch (Exception e)
            {
                if (mensaje == null)
                {
                    mensaje = new MensajeTransaccion();
                    mensaje.CodigoRespuesta = "CC-000001";
                    mensaje.MensajeRespuesta = "Ocurrió un problema al guardar la base de la matriz de indicadores de gestión. " + e.Message;
                }
            }
            //ViewBag.mensajeRespuesta = mensaje.MensajeRespuesta;
            return Json(mensaje.MensajeRespuesta);

            
        }

        //public JsonResult Aliado()
        //{
        //    List<MatrizGestionViewModel> listaAliado = null;
        //    List<SelectListItem> Lista = new List<SelectListItem>();
        //    MatrizGestionViewModel matrix = new MatrizGestionViewModel();
        //    try
        //    {
        //        int valorLista = (int)MatrizGestionServicio.ListaMatrizGestion.Lista_Aliado;
        //        listaAliado = MatrizGestionService.ListadoServicio(valorLista, matrix);

        //        Lista.Add(new SelectListItem { Text = Convert.ToString("Todos"), Value = Convert.ToString("Todos") });
        //        foreach (var val in listaAliado)
        //        {
        //            Lista.Add(new SelectListItem { Text = Convert.ToString(val.nombre), Value = Convert.ToString(val.nombre) });
        //        }
        //    }
        //    catch (Exception ex)
        //    {
        //        throw ex;
        //    }
        //    ViewBag.Aliado =Lista;
        //    return Json(new SelectList(Lista, "Value", "Text", JsonRequestBehavior.AllowGet));
        //}
        
        public JsonResult NombreBase()
        {
            
            List<SelectListItem> ListaTR = new List<SelectListItem>();
            List<OperacionesViewModel> op = new List<OperacionesViewModel>();
            
            ListaTR.Add(new SelectListItem { Text = Convert.ToString("Prestamo promedio"), Value = Convert.ToString("Prestamo promedio") });
            ListaTR.Add(new SelectListItem { Text = Convert.ToString("Porcentaje máximo de enajenación"), Value = Convert.ToString("Porcentaje máximo de enajenación") });
            //ListaTR.Add(new SelectListItem { Text = Convert.ToString("Cartera (aparatos)"), Value = Convert.ToString("Cartera (aparatos)") });
            //ListaTR.Add(new SelectListItem { Text = Convert.ToString("Cartera (celulares)"), Value = Convert.ToString("Cartera (celulares)") });
            //ListaTR.Add(new SelectListItem { Text = Convert.ToString("Cartera (joyería)"), Value = Convert.ToString("Cartera (joyería)") });
            ListaTR.Add(new SelectListItem { Text = Convert.ToString("Cartera total"), Value = Convert.ToString("Cartera total") });
            ListaTR.Add(new SelectListItem { Text = Convert.ToString("Capital prestado"), Value = Convert.ToString("Capital prestado") });
            ListaTR.Add(new SelectListItem { Text = Convert.ToString("Ingresos (empeño)"), Value = Convert.ToString("Ingresos (empeño)") });
            ListaTR.Add(new SelectListItem { Text = Convert.ToString("Clientes nuevos empeños"), Value = Convert.ToString("Clientes nuevos empeños") });
            ListaTR.Add(new SelectListItem { Text = Convert.ToString("Clientes nuevos ventas"), Value = Convert.ToString("Clientes nuevos ventas") });
            ListaTR.Add(new SelectListItem { Text = Convert.ToString("Ingreso venta (aparatos)"), Value = Convert.ToString("Ingreso venta (aparatos)") });
            ListaTR.Add(new SelectListItem { Text = Convert.ToString("Ingreso venta (celulares)"), Value = Convert.ToString("Ingreso venta (celulares)") });
            ListaTR.Add(new SelectListItem { Text = Convert.ToString("Ingreso venta (joyería)"), Value = Convert.ToString("Ingreso venta (joyería)") });
            //ListaTR.Add(new SelectListItem { Text = Convert.ToString("Ingreso total (empeños - ventas)"), Value = Convert.ToString("Ingreso total (empeños - ventas)") });
            
            ViewBag.NombreBase = new SelectList(ListaTR, "Value", "Text");
            return Json(new SelectList(ListaTR, "Value", "Text", JsonRequestBehavior.AllowGet));
        }

        //Busqueda de la base por medio de su clave(catalogo mantenimiento base del Indicador de la matrz de indicadores de gestion)
        public ActionResult OpcionesBase(int BaseID)
        {
            OperacionesViewModel BaseCon = null;

            try
            {
                NombreBase();
                //Sucursal();
                //CONSULTA DE TODOS LOS PARAMETROS
                var valorCon = (int)OperacionesServicio.Consulta.Con_Base;                
                BaseCon = OperacionService.ConsultaBase(valorCon, BaseID);               
            }
            catch(Exception ex)
            {
                throw ex;
            }
            return PartialView(BaseCon);
        }


        //Metodo para actualizar la base
        [HttpPost]
        public JsonResult ActualizarBase(OperacionesViewModel mantenimientoBase)
        {
            MensajeTransaccion mensaje = null;
            try
            {
               
                int valor = (int)OperacionesServicio.Actualizar.Act_Base;
                mensaje = OperacionService.ActualizarBaseServicio(mantenimientoBase, valor);

            }
            catch (Exception e)
            {
                if (mensaje == null)
                {
                    mensaje = new MensajeTransaccion();
                    mensaje.CodigoRespuesta = "CC-000002";
                    mensaje.MensajeRespuesta = "Ocurrió un problema al modificar la base. " + e.Message;
                }
            }
            return Json(mensaje.MensajeRespuesta);
        }
        
        public ActionResult ManDiaHabil()
        {
            List<OperacionesViewModel> lista = null;
            try
            {
                int valorLista = (int)OperacionesServicio.Lista.Lista_DiasHabiles;
                lista = OperacionService.ListarDiaHabilServicio(valorLista);
            }
            catch (Exception)
            {
                throw;
            }
            return View(lista);
        }

        //Alta de nuevO dia habil de la matriz de gestion en el catalogo de operaciones.
        public JsonResult AltaDiaHabil(OperacionesViewModel MatrizGestion)
        {

            MensajeTransaccion mensaje = null;

            try
            {
                //mensaje = ProductoSer.AltaProductoServicio(producto, usuarioResponse);
                mensaje = OperacionService.AltaDiaHabilServicio(MatrizGestion);
            }
            catch (Exception e)
            {
                if (mensaje == null)
                {
                    mensaje = new MensajeTransaccion();
                    mensaje.CodigoRespuesta = "CC-000002";
                    mensaje.MensajeRespuesta = "Ocurrió un problema al guardar el dia habil de la matriz de indicadores de gestión. " + e.Message;
                }
            }
            //ViewBag.mensajeRespuesta = mensaje.MensajeRespuesta;

SistemaBase/Controllers/MenuLateralController.cs
using ENTIDADES.Login;
using ENTIDADES.Seguridad;
using SERVICIO.Seguridad;
using SistemaBase.Filters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SistemaBase.Controllers
{
    public class MenuLateralController : Controller
    {

        UsuarioViewModel usuarioResponse = new UsuarioViewModel();
        

        // GET: MenuLateral
        public ActionResult MenuLateral()
        {
            return PartialView();
        }


        public static bool TienePermiso(RolesPermisos valor, string Cvepuesto)
        {
            PermisoEmpleadoViewModel permiso = new PermisoEmpleadoViewModel();
            permiso = MenuLateralController.Get(Convert.ToInt32(valor), Cvepuesto);
            if (permiso.RolID.Equals(0))
            {
                return false;
            }
            else
            {
                return true;
            }
        }

        public static PermisoEmpleadoViewModel Get(int valor, string Cvepuesto)
        {

            PermisoEmpleadoViewModel permisoo = new PermisoEmpleadoViewModel();
            
            PermisoEmpleadoServicio perm = new PermisoEmpleadoServicio();
            PermisoEmpleadoViewModel modelo = new PermisoEmpleadoViewModel();
            
            permisoo = perm.ConsultaPermisoEmpleado(valor, Cvepuesto);
            return permisoo;
        }



    }
}

SistemaBase/Controllers/RH/IRPController.cs
using ENTIDADES.RH;
using SERVICIO.RH;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace SistemaBase.Controllers.RH
{
    public class IRPController : Controller
    {

        SERVICIO.RH.IRPServicio IRPservices = new SERVICIO.RH.IRPServicio();

        // GET: IRP
        public ActionResult Index()
        {
            //IRPView();
            // return View();
            List<IRPViewModel> listaIRP = null;
            try
            {
                int valorLista = (int)IRPServicio.ListaIRP.IRP;
                listaIRP = IRPservices.ListarIRPServicio(valorLista);
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return View(listaIRP);
        }


        //public ActionResult prueb()
        //{
        //    // return View();
        //    List<IRPViewModel> listaIRP = null;
        //    try
        //    {
        //        int valorLista = (int)IRPServicio.ListaIRP.IRP;
        //        listaIRP = IRPservices.ListarIRPServicio(valorLista);
        //    }
        //    catch (Exception ex)
        //    {
        //        throw ex;
        //    }
        //    return PartialView(listaIRP.ToList());
        //}

        public JsonResult IRP()
        {
            
            // return View();
            List<IRPViewModel> listaIRP = null;
            try
            {
                int valorLista = (int)IRPServicio.ListaIRP.IRP;
                listaIRP = IRPservices.ListarIRPServicio(valorLista);
            }
            catch (Exception ex)
            {
                throw ex;
            }

            //ViewBag.Semana = (new JavaScriptSerializer()).Serialize(listaIRP);
            //listaIRP.ToString()
            //return Json(ViewBag.Semana);

            var valor = (new JavaScriptSerializer().Serialize(listaIRP));
            return Json(valor);
           // return Json(listaIRP, JsonRequestBehavior.AllowGet);

        }
        public JsonResult IRPAlta()
        {
            List<IRPViewModel> listaIRP = null;
            try
            {
                int valorLista = (int)IRPServicio.ListaIRP.IRP_Alta;
                listaIRP = IRPservices.ListarIRPServicio(valorLista);
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return Json(listaIRP.ToList());
        }
        public JsonResult IRPBaja()
        {
            List<IRPViewModel> listaIRP = null;
            try
            {
                int valorLista = (int)IRPServicio.ListaIRP.IRP_Baja;
                listaIRP = IRPservices.ListarIRPServicio(valorLista);
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return Json(listaIRP.ToList());
        }
        public JsonResult IRPAcumulado()
        {
            List<IRPViewModel> listaIRP = null;
            try
            {
                int valorLista = (int)IRPServicio.ListaIRP.IRP_Acumulado;
                listaIRP = IRPservices.ListarIRPServicio(valorLista);
            }
            catch (Exception ex)
            {
                throw ex;
            }
            //return Json(listaIRP.ToList());
            return Json(listaIRP);
        }



        




    }
}

SistemaBase/Views/Shared/MenuLateral.cshtml
@using ENTIDADES.Login
@{
    var usuario = (Session["usuario"] as UsuarioViewModel).CodigoAlterno;
    var nombre = (Session["usuario"] as UsuarioViewModel).NombreEmp;
    var Cvepuesto = (Session["usuario"] as UsuarioViewModel).CvePuestoEmpleado;
    var puesto = (Session["usuario"] as UsuarioViewModel).NomPuestoEmp;
    //var nombre = (Session["usuario"] as LoginViewModel).Login;
    //var nombre = (Session["usuario"] as UsuarioViewModel).NombreEmp;
    //var departamento = (Session["usuario"] as UsuarioViewModel).NomDepartamdentoEmp;
    //var puesto = (Session["usuario"] as UsuarioViewModel).NomPuestoEmp;
    //var Cvepuesto = (Session["usuario"] as UsuarioViewModel).CvePuestoEmpleado;
}


<ul class="sidebar-menu" data-widget="tree">
    <li class="header">MENÚ</li>
    <li class="active treeview">

    </li>

    @if (SistemaBase.Controllers.MenuLateralController.TienePermiso(SistemaBase.Filters.RolesPermisos.RH, Cvepuesto))
    {
        <li class="treeview">
            <a href="#">
                <i class="fa fa-address-book-o" aria-hidden="true"></i>
                <span>RH</span>
                <span class="pull-right-container">
                    <i class="fa fa-line-chart" aria-hidden="true"></i>
                </span>
            </a>
            <ul class="treeview-menu">
                <li>@Html.ActionLink("Rotación personal", "Index", "IRP")</li>
            </ul>
        </li>
    }
    @if (SistemaBase.Controllers.MenuLateralController.TienePermiso(SistemaBase.Filters.RolesPermisos.Operaciones, Cvepuesto))
    {
        <li class="treeview">
            <a href="#">
                <i class="fa fa-cog" aria-hidden="true"></i>
                <span>Operaciones</span>
                <span class="pull-right-container">
                    <i class="fa fa-line-chart" aria-hidden="true"></i>
                </span>
            </a>
            <ul class="treeview-menu">
                <li>@Html.ActionLink("Promedio préstamo", "Index", "PromedioPrestamo")</li>
                <li>@Html.ActionLink("Matriz de gestión", "MatrizGestion", "MatrizGestion")</li>

                <li>@Html.ActionLink("Matriz de gestión DevExpress", "MatrizGestionDevExpress", "MatrizGestion")</li>
            </ul>
        </li>
    }
    @if (SistemaBase.Controllers.MenuLateralController.TienePermiso(SistemaBase.Filters.RolesPermisos.Mantenimiento, Cvepuesto))
    {
        <li class="treeview">
            <a href="#">
                <i class="fa fa-cog" aria-hidden="true"></i>
                <span>Mantenimiento</span>
                <span class="pull-right-container">
                    <i class="fa fa-line-chart" aria-hidden="true"></i>
                </span>
            </a>
            <ul class="treeview-menu">
                <li>@Html.ActionLink("Meta de operación", "MantMatrizGestion", "Operaciones")</li>
                <li>@Html.ActionLink("Días inhabiles", "ManDiaHabil", "Operaciones")</li>
            </ul>
        </li>
    }
    @if (SistemaBase.Controllers.MenuLateralController.TienePermiso(SistemaBase.Filters.RolesPermisos.Seguridad, Cvepuesto))
    {
        <li class="treeview">
            <a href="#">
                <i class="fa fa-cog" aria-hidden="true"></i>
                <span>Seguridad</span>
                <span class="pull-right-container">
                    <i class="fa fa-line-chart" aria-hidden="true"></i>
                </span>
            </a>
            <ul class="treeview-menu">
                <li>@Html.ActionLink("Permisos", "Index", "Permisos")</li>
                @*<li>@Html.ActionLink("Control inicio sesión", "ControlLogin", "Permisos")</li>*@
                <li>@Html.ActionLink("Control indicadores operaciones", "ControlIndicadorOperaciones", "Permisos")</li>
                <li>@Html.ActionLink("Permiso por sucursal", "PermisoOperaciones", "Permisos")</li>
            </ul>
        </li>
    }

</ul>

SistemaBase/Views/Shared/_AjaxGridPager.cshtml
@model Grid.Mvc.Ajax.GridExtensions.AjaxGridPager
@if (Model.Pages < 2)
{
    return;
}

<div class="grid-footer">
    <div class="grid-pager">
        <ul class="pagination">
            <li><a href="#" class="grid-prev-page" title="Previous Page" style="display: none"><span class="fa fa-backward"></span></a></li>
            @{if (Model.Pages > Model.PagePartitionSize + 2 &&
                  Model.PagePartitionSize > 0)
            {
                <li class="active"><a class="grid-page-link" data-page="1">1</a></li>
                <li><a href="#" class="grid-pageSetLink prev" style="display: none;" data-pageset='1' data-partitionsize="@Model.PagePartitionSize">...</a></li>
                for (int i = 1; i < Model.PagePartitionSize + 1; i++)
                {
                    var currentPage = i + 1;
                    <li><a href="#" class="grid-page-link" data-page='@currentPage'>@currentPage</a></li>
                }

                <li><a href="#" class="grid-pageSetLink next" data-pageset='2' data-partitionsize="@Model.PagePartitionSize">...</a></li>
                <li><a href="#" class="grid-page-link" data-page='@Model.Pages'>@Model.Pages</a></li>
            }
            else
            {
                <li class="active"><a class="grid-page-link" data-page="1">1</a></li>
                for (int i = 1; i < Model.Pages; i++)
                {
                    var currentPage = i + 1;
                    <li><a href="#" class="grid-page-link" data-page='@currentPage'>@currentPage</a></li>
                }
            }
            }
            <li><a href="#" title="Next Page" class="grid-next-page"><span class="fa fa-forward"></span></a></li>
        </ul>
    </div>
</div>

SistemaBase/Views/Shared/_Grid.cshtml
@using GridMvc.Columns
@model GridMvc.IGrid
@if (Model == null) { return; }
@if (Model.RenderOptions.RenderRowsOnly)
{
    @RenderGridBody();
}
else
{
    <div class="grid-mvc" data-lang="@Model.Language" data-gridname="@Model.RenderOptions.GridName" data-selectable="@Model.RenderOptions.Selectable.ToString().ToLower()" data-multiplefilters="@Model.RenderOptions.AllowMultipleFilters.ToString().ToLower()">
        @*table-responsive*@
        <div class="grid-wrap">
            <table class="table table-hover table-bordered grid-table table-striped" id="grid">
                <thead>
                    @RenderGridHeader()
                </thead>
                <tbody id="SucBody">
                    @RenderGridBody()
                </tbody>
            </table>
            @RenderGridPager()
        </div>
    </div>
}
@helper RenderGridBody()
{
if (!Model.ItemsToDisplay.Any())
{
        <tr class="grid-empty-text">
            <td colspan="@Model.Columns.Count()">
                @Model.EmptyGridText
            </td>
        </tr>
}
else
{
    foreach (object item in Model.ItemsToDisplay)
    {
            <tr class="grid-row @Model.GetRowCssClasses(item)">
                @foreach (IGridColumn column in Model.Columns)
                {
                    @column.CellRenderer.Render(column, column.GetCell(item))
                }
            </tr>
    }
}
}
@helper RenderGridHeader()
{
    <tr>
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.HeaderRenderer.Render(column)
        }
    </tr>
}
@helper RenderGridPager()
{
if (Model.EnablePaging && Model.Pager != null)
{
        <div class="grid-footer text-center">
            @Html.Partial(Model.Pager.TemplateName, Model.Pager)
        </div>
}
}

SistemaBase/Views/Shared/_GridPager.cshtml
@model GridMvc.Pagination.GridPager
@if (Model == null || Model.PageCount <= 1)
{
    return;
}
<div class="grid-pager">
    <ul class="pagination">
        @if (Model.CurrentPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(Model.CurrentPage - 1)">«</a>
            </li>
        }

        @if (Model.StartDisplayedPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(1)">1</a>
            </li>
            if (Model.StartDisplayedPage > 2)
            {
                <li><a href="@Model.GetLinkForPage(Model.StartDisplayedPage - 1)">...</a></li>
            }
        }
        @for (int i = Model.StartDisplayedPage; i <= Model.EndDisplayedPage; i++)
        {
            if (i == Model.CurrentPage)
            {
                <li class="active"><span>@i</span></li>
            }
            else
            {
                <li><a href="@Model.GetLinkForPage(i)">@i</a></li>
            }
        }
        @if (Model.EndDisplayedPage < Model.PageCount)
        {
            if (Model.EndDisplayedPage < Model.PageCount - 1)
            {
                <li><a href="@Model.GetLinkForPage(Model.EndDisplayedPage + 1)">...</a></li>
            }
            <li><a href="@Model.GetLinkForPage(Model.PageCount)">@Model.PageCount</a></li>
        }
        @if (Model.CurrentPage < Model.PageCount)
        {
            <li><a href="@Model.GetLinkForPage(Model.CurrentPage + 1)">»</a></li>
        }
    </ul>
</div>

SistemaBase/Views/Shared/_jsTreeDemo.cshtml
@{
    Layout = null;

    ViewBag.Title = string.Format("jsTree 3.1.1 - {0}", ViewBag.Title);
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    <link rel="stylesheet" href="http://static.jstree.com/3.0.0-beta5/assets/bootstrap/css/bootstrap.css" />
    <link href="~/Content/jsTree/docs.css" rel="stylesheet" />
    <link href="~/Content/jsTree/themes/default/style.css" rel="stylesheet"/>
    <script src="~/Scripts/jquery-1.9.1.js"></script>
    <script src="~/Scripts/jsTree3/jstree.js"></script>

</head>
<body>
    <header id="head">
        <div class="container">
            <div class="row">
                <div class="col-md-3 col-sm-12">
                    <h1 id="logo"><a href="http://jstree.com">jsTree - jQuery tree plugin<span>3.1.1</span></a></h1>
                </div>
                <div class="col-md-6 col-sm-8">
                    <nav>
                        <ul class="nav nav-pills" id="menu"><li class="active"><li class="active"><a href="/jsTree3/Demo"> @ViewBag.Title</a></ul>
</nav>
                </div>
                <div class="col-md-3 col-sm-4">

                </div>
            </div>
        </div>
    </header>
    <div>
        <div class="container" id="content">
            <div class="row page" id="docs" style="display:block;">
                @RenderBody()
            </div>
        </div>
    </div>
</body>
</html>