SistemaBase/Controllers/Seguridad/PermisosController.cs
using ENTIDADES.Base;
using ENTIDADES.Login;
using ENTIDADES.Seguridad;
using SERVICIO.Seguridad;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace SistemaBase.Controllers.Seguridad
{
    public class PermisosController : Controller
    {
        SERVICIO.Seguridad.PermisoEmpleadoServicio ServicioSeguridad = new SERVICIO.Seguridad.PermisoEmpleadoServicio();

        // GET: Seguridad
        public ActionResult Index()
        {

            List<TreeViewNode> nodes = new List<TreeViewNode>();    
            List<PermisoEmpleadoViewModel> lista = null;

            AccesoViewModel listaModel = new AccesoViewModel();

            try
            {
                int Lista_PermisoRol = (int)PermisoEmpleadoServicio.Acceso.Lista_PermisoRol;
                int Lista_PermisoMod = (int)PermisoEmpleadoServicio.Acceso.Lista_PermisoMod;
                listaModel = ServicioSeguridad.PuestosPermisoServicio(Lista_PermisoRol, Lista_PermisoMod);

                //Bucle para agregar los nodos principales ROL, PUETOS
                foreach (PermisoEmpleadoViewModel rol in listaModel.Rol)
                {
                    nodes.Add(new TreeViewNode { id = rol.PermisoID.ToString(), parent = "#", text = rol.Modulo });
                }
                //Bucle para agregar los nodos hijos //cATALOGOS//Modulos
                foreach (PermisoEmpleadoViewModel modulo in listaModel.Modulo)
                {
                    //nodes.Add(new TreeViewNode { id = modulo.PermisoID.ToString() + "-" + modulo.Nombre.ToString(), parent = modulo.RolID.ToString(), text = modulo.Modulo });
                    nodes.Add(new TreeViewNode { id = modulo.PermisoID.ToString() + "-" + modulo.Modulo.ToString(), parent = modulo.RolID.ToString(), text = modulo.Modulo });
                }
                //Serializar en cadena Json
                ViewBag.Json = (new JavaScriptSerializer()).Serialize(nodes);
                
            }
            catch (Exception)
            {
                throw;
            }
            
            return View();
        }

        [HttpPost]
        public ActionResult Index(string selectedItems)
        {
            List<TreeViewNode> items = (new JavaScriptSerializer()).Deserialize<List<TreeViewNode>>(selectedItems);
            return RedirectToAction("Index");
        }


        public JsonResult RolPermiso()
        {
            AccesoViewModel acceso = null;

            try
            {

                //var valorPer = (int)PermisoEmpleadoServicio.Acceso.Lista_Permiso;
                //var valorMod = (int)PermisoEmpleadoServicio.Acceso.Lista_Modulo;
                //var valorPue = (int)PermisoEmpleadoServicio.Acceso.Lista_Puesto;

                var valorPer = (int)PermisoEmpleadoServicio.Acceso.Lista_Permiso;
                var valorMod = (int)PermisoEmpleadoServicio.Acceso.Lista_Modulo;
                var valorPue = (int)PermisoEmpleadoServicio.Acceso.Lista_Puesto;


                acceso = ServicioSeguridad.AccesoServicio(valorPer, valorMod, valorPue);
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return Json(acceso);
        }


        //Lleva el control de quien inicie sesion
        public ActionResult ControlLogin()
        {
            List<PermisoEmpleadoViewModel> lista = null;
            PermisoEmpleadoViewModel permiso = new PermisoEmpleadoViewModel();
            try
            {
                int valorLista = (int)PermisoEmpleadoServicio.Acceso.Lista_AccesoLogin;
                lista = ServicioSeguridad.ControlAccesoServicio(permiso, valorLista);
            }
            catch (Exception)
            {
                throw;
            }
            return View(lista);
            //return View();
        }

        public ActionResult ControlIndicadorOperaciones()
        {
            List<PermisoEmpleadoViewModel> lista = null;
            lista = new List<PermisoEmpleadoViewModel>();
            return View(lista);
        }

        //LLeva control, cuando se selecciona la sucursal en los indicadores de operaciones
        [HttpPost]
        public ActionResult ControlIndicadorOperaciones(PermisoEmpleadoViewModel permiso)
        {
            List<PermisoEmpleadoViewModel> lista = null;
            try
            {
                int valorLista = (int)PermisoEmpleadoServicio.Acceso.Lista_AccesoOperacion;
                lista = ServicioSeguridad.ControlAccesoServicio(permiso, valorLista);
            }
            catch (Exception)
            {
                throw;
            }
            return PartialView("gridControlIndOperacion",lista);

        }
        
        //Año, Mes y sucursal 
        public JsonResult Control()
        {
            List<PermisoEmpleadoViewModel> lista = null;

            AccesoViewModel listaControlModel = new AccesoViewModel();

            try
            {
                int Lista_Anio = (int)PermisoEmpleadoServicio.Acceso.Lista_Anio;
                int Lista_Mes = (int)PermisoEmpleadoServicio.Acceso.Lista_Mes;
                int Lista_Sucursal = (int)PermisoEmpleadoServicio.Acceso.Lista_Sucursal;


                listaControlModel = ServicioSeguridad.ControlServicio(Lista_Anio, Lista_Mes, Lista_Sucursal);


            }
            catch (Exception)
            {
                throw;
            }
            
            return Json(listaControlModel, JsonRequestBehavior.AllowGet);
        }
        
        //Agregar permiso por medio del puesto
        public JsonResult AddAccess(PermisoEmpleadoViewModel permisoModel)
                {

                    MensajeTransaccion mensaje = null;
                    try
                    {
                        mensaje = ServicioSeguridad.AltaPermisoServicio(permisoModel);
                    }
                    catch (Exception)
                    {
                        throw;
                    }
                    return Json(mensaje.MensajeRespuesta);
                    //return View();
                }

        //Año, Mes y sucursal 
        public ActionResult PermisoOperaciones()
        {
            
            List<TreeViewNode> nodes = new List<TreeViewNode>();
            List<PermisoEmpleadoViewModel> lista = null;

            AccesoViewModel listaModel = new AccesoViewModel();

            try
            {
                //acceso.Rol = ListadoPermisoEmpleado.ListaTreeEmpDAO(emp);
                //acceso.Modulo = ListadoPermisoEmpleado.ListaTreeEmpSucDAO(modulo);

                int Lista_PermisoMod = (int)PermisoEmpleadoServicio.Acceso.Lista_EmpSuc;
                int Lista_PermisoEmp = (int)PermisoEmpleadoServicio.Acceso.Lista_Emp;

                listaModel = ServicioSeguridad.TreePuestosPermisoServicio(Lista_PermisoMod, Lista_PermisoEmp);

                //Bucle para agregar los nodos principales ROL, PUETOS
                foreach (PermisoEmpleadoViewModel rol in listaModel.Rol)
                {
                    nodes.Add(new TreeViewNode { id = rol.Usuario.ToString(), parent = "#", text = rol.Usuario });
                }
                //Bucle para agregar los nodos hijos //cATALOGOS//Modulos
                foreach (PermisoEmpleadoViewModel modulo in listaModel.Modulo)
                {
                    //nodes.Add(new TreeViewNode { id = modulo.PermisoID.ToString() + "-" + modulo.Nombre.ToString(), parent = modulo.RolID.ToString(), text = modulo.Modulo });
                    nodes.Add(new TreeViewNode { id = modulo.SucursalID.ToString() + "-" + modulo.Sucursal.ToString(), parent = modulo.Usuario.ToString(), text = modulo.Sucursal });
                }
                //Serializar en cadena Json
                ViewBag.Json = (new JavaScriptSerializer()).Serialize(nodes);

            }
            catch (Exception ex)
            {
                throw ex;
            }


            return View();
        }

        //PUESTO, EMPLEADO 
        public JsonResult PuestoOperacionesInd()
        {
            //AccesoViewModel acceso = null;
            List<PermisoEmpleadoViewModel> acceso = null;
            try
            {
                var valorPto = (int)PermisoEmpleadoServicio.Acceso.Lista_PuestoDBDIN;

                acceso = new List<PermisoEmpleadoViewModel>();
                acceso = ServicioSeguridad.PuestoPermisoServicio(valorPto);
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return Json(acceso);
        }
        
        public JsonResult EmpleadoOperacionesInd(string puestoID)
        {
            //AccesoViewModel acceso = null;
            List<PermisoEmpleadoViewModel> acceso = null;
            try
            {
                var valorEdo = (int)PermisoEmpleadoServicio.Acceso.Lista_EmpleadoDBDIN;
                //var valorSal = (int)PermisoEmpleadoServicio.Acceso.Lista_SucSucursalDBDIN;
                acceso = new List<PermisoEmpleadoViewModel>();
                acceso = ServicioSeguridad.EmpleadoPermisoServicio(valorEdo, puestoID);
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return Json(acceso);
        }

        public JsonResult AltaEmpSuc(PermisoEmpleadoViewModel permisoModel)
        {

            MensajeTransaccion mensaje = null;
            try
            {
                mensaje = ServicioSeguridad.AltaEmpSucServicio(permisoModel);
            }
            catch (Exception)
            {
                throw;
            }
            return Json(mensaje.MensajeRespuesta);
            //return View();
        }
        //Elimina al usuario con las sucursales, (permisos para que usuario pueda ver las sucursales en la pantalla principal)
        public JsonResult DeletePermiso(UsuarioViewModel usr)
        {

SistemaBase/Views/Permisos/ControlIndicadorOperaciones.cshtml
@model IEnumerable<ENTIDADES.Seguridad.PermisoEmpleadoViewModel>
@using GridMvc.Html
@{
    ViewBag.Title = "ControlIndicadorOperaciones";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="content">
    <div class="box box-info" style="min-height: 506px;">
        <div class="box-header" style="padding-top:0px!important;">
            <h4 class="col-md-12 Indicacion text-center">Control para indicadores: Matriz de indicadores de gestión</h4>
        </div>
        <hr />
        <div class="container-fluid" style="margin-bottom:30px">
            @*@using (Html.BeginForm("ControlIndicadorOperaciones", "Permisos", FormMethod.Post, new { @class = "form-horizontal login100-form", enctype = "multipart/form-data" }))
            {

                <div class="col-md-3">
                    <div class="row mb-3">
                        <label class="col-sm-4 col-form-label Indicacion text-center" style="width:min-content;">Año:</label>
                        <div class="col-sm-8">
                            @Html.DropDownList("anio", new SelectList(string.Empty, "Value", "Text"), "- seleccionar -", new { @name = "anio", @style = "display:block; width:100%" })
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="row mb-3">
                        <label class="col-sm-4 col-form-label Indicacion text-center" style="width:min-content;">Mes:</label>
                        <div class="col-sm-8">
                            @Html.DropDownList("mes", new SelectList(string.Empty, "Value", "Text"), "- seleccionar -", new { @name = "mes", @style = "display:block; width:100%" })
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="row mb-3">
                        <label class="col-md-6 col-form-label Indicacion" style="width:min-content">Sucursal:</label>
                        <div class="col-sm-6">
                            @Html.DropDownList("sucursal", new SelectList(string.Empty, "Value", "Text"), "- seleccionar -", new { @name = "Sucursal", @style = "display:block; width:100%" })
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="row">
                        <div class="col-md-6">
                            <button type="submit" class="btnOk">Consultar</button>
                        </div>
                    </div>
                </div>

            }*@



            @using (Ajax.BeginForm("ControlIndicadorOperaciones", "Permisos", new AjaxOptions
            {
                HttpMethod = "POST",
                InsertionMode = InsertionMode.Replace,
                UpdateTargetId = "Generar",
                OnSuccess = "OnSuccess",
                OnFailure = "OnFailure"
            }))
            {
                @Html.ValidationSummary(true)
                <div class="col-md-3">
                    <div class="row mb-3">
                        <label class="col-sm-4 col-form-label Indicacion text-center" style="width:min-content;">Año:</label>
                        <div class="col-sm-8">
                            @Html.DropDownList("anio", new SelectList(string.Empty, "Value", "Text"), "- seleccionar -", new { @name = "anio", @style = "display:block; width:100%" })
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="row mb-3">
                        <label class="col-sm-4 col-form-label Indicacion text-center" style="width:min-content;">Mes:</label>
                        <div class="col-sm-8">
                            @Html.DropDownList("mes", new SelectList(string.Empty, "Value", "Text"), "- seleccionar -", new { @name = "mes", @style = "display:block; width:100%" })
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="row mb-3">
                        <label class="col-md-6 col-form-label Indicacion" style="width:min-content">Sucursal:</label>
                        <div class="col-sm-6">
                            @Html.DropDownList("sucursal", new SelectList(string.Empty, "Value", "Text"), "- seleccionar -", new { @name = "Sucursal", @style = "display:block; width:140%" })
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="row">
                        <div class="col-md-6">
                            <button type="submit" class="ok">Consultar</button>
                        </div>
                    </div>
                </div>
            }
        </div>


        <div class="box-body" id="Generar">
            
          
        </div>
    </div>
</div>
<style>
    .dropdown.dropdown-menu.grid-dropdown.opened {
        margin-left: -67px !important;
    }

    .grid-dropdown-arrow {
        left: 63px !important;
    }
</style>

<script>
    //año, mes, sucursal
    $(document).ready(function () {

        $.ajax({
            type: 'POST',
            url: '@Url.Action("Control")',
            dataType: 'json',
            success: function (response) {

                console.log(response);
                $.each(response.anio, function (i, anioReponse) {
                    $("#anio").append('<option value="' + anioReponse.anio + '">' + anioReponse.anio + '</option>');
                });

                $.each(response.mes, function (i, mesResponse) {
                    $("#mes").append('<option value="' + mesResponse.Total + '">' + mesResponse.mes + '</option>');
                });

                $.each(response.sucursal, function (i, sucursalResponse) {
                    $("#sucursal").append('<option value="' + sucursalResponse.Sucursal + '">' + sucursalResponse.Sucursal + '</option>');
                });

            },
        });
    });


    function OnFailure() {
        alert("Intente de nuevo");
    }
</script>

SistemaBase/Views/Permisos/ControlLogin.cshtml
@model IEnumerable<ENTIDADES.Seguridad.PermisoEmpleadoViewModel>
@using GridMvc.Html
@{
    ViewBag.Title = "ControlLogin";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="content">
    <div class="box box-info" style="min-height: 506px;">
        <div class="box-header" style="padding-top:0px!important;">
            <h4 class="col-md-12 Indicacion text-center">Control de acceso (Inicio sesión)</h4>
        </div>
        <hr />
        <div class="box-body">
            @Html.Grid(Model).Columns(columns =>
       {
           columns.Add(c => c.Usuario).Titled("Usuario").Css("gridCel").Sortable(true).Filterable(true).Title.Trim();
           columns.Add(c => c.FechaVar).Titled("Fecha").Css("gridCel").Sortable(true).Filterable(true);
           columns.Add(c => c.Total).Titled("Total").Css("gridCel").Sortable(true).Filterable(true);
       }).Sortable(true).EmptyText("Sin Registros").WithPaging(15, 5)
        </div>
    </div>
</div>

<style>
    .dropdown.dropdown-menu.grid-dropdown.opened {
        margin-left: -67px !important;
    }

    .grid-dropdown-arrow {
        left: 63px !important;
    }
</style>

SistemaBase/Views/Permisos/Index.cshtml
@model IEnumerable<ENTIDADES.Seguridad.PermisoEmpleadoViewModel>
@using GridMvc.Html
@{
    ViewBag.Title = "Acceso";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@*<script src="~/Scripts/jquery-2.2.3.js"></script>*@
<div class="content">
    <div class="box box-info" style="min-height: 506px;">
        <div class="box-header" style="padding-top:10px!important;">
            <span class="Indicacion text-center" style="display:inherit;">Permisos/Acceso</span>
        </div>
        <hr />
        <div class="box-body">
            <div class="container col-md-12" style="margin: 0px 0px 20px 0px!important;">
                <button class="ok" id="AddAcceso" type="button">Nuevo</button>
            </div>

            <div id="jstree"></div>
            @*@using (Html.BeginForm("Index", "Home", FormMethod.Post))
            {
                <input type="hidden" name="selectedItems" id="selectedItems" />
                <input type="submit" value="Submit" />
            }*@

       <script type="text/javascript">
        $(function () {
            $('#jstree').on('changed.jstree', function (e, data) {
                var i, j;
                var selectedItems = [];
                for(i = 0, j = data.selected.length; i < j; i++) {

                    //Busca la identificación.
                    var id = data.selected[i];

                    //Quite el ParentId.
                    //if(id.indexOf('-') != -1){
                    //    id = id.split("-")[1];
                    //}

                    //Agregue el nodo a la matriz JSON.
                    selectedItems.push({
                        text: data.instance.get_node(data.selected[i]).text,
                        id: id,
                        parent: data.node.parents[0]
                    });

                    //Al seleccionar item mandar a los detalles del ticket
                    if(data.node.parents[0]=="#"){ 

                        $('#ShowModificar').modal("show");
                        $("#txt1").val(data.node.text);
                        $("#cvePuesto").val(id);

                     
                        var $demo = $("#jstree");
                        var nodes =  $demo.jstree("get_top_selected", true);

                        //Selects all of the children of each selected node including folders
                        if(nodes.length > 0){
                            nodes.forEach(function(node, i){
                                $demo.jstree("select_node", node.children_d, true, false);
                            });
                        }

                        var fileNodes = $demo.jstree("get_bottom_selected", false);

                        //We now need to deselect everything and only select the file nodes
                        $demo.jstree("deselect_all", true);
                        $demo.jstree("select_node", fileNodes, true, false);
                        
                        
                        $("#prueb").val(fileNodes);

                   
                    }
                }
                //Serialize the JSON Array and save in HiddenField.
                //$('#selectedItems').val(JSON.stringify(selectedItems));
            }).jstree({
                "core": {
                    "themes": {
                        "variant": "large"
                    },
                    "data": @Html.Raw(ViewBag.Json),
                    },
                //"checkbox": {
                //    "keep_selected_style": false
                //},
                //"plugins": ["wholerow", "checkbox"],
                //"plugins": ["types", "conditionalselect", "sort","dnd" ],
                "plugins": ["themes", "json_data"],
            });
        });
            </script>
            </div>
        </div>
</div>
<style>
  div#jstree {
    margin-top: 50px!important;
}
</style>

<!-- Modal para agregar nuevos dias inhabiles -->
<div class="modal fade" id="ShowAlta" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title Indicacion" id="staticBackdropLabel">Nuevo permiso por puesto</h4>
            </div>
            <form id="FormProducto">
                <div class="modal-body">
                    
                    <h4 class="Indicacion">Puesto:</h4>
                   @Html.DropDownList("PuestoID", new SelectList(string.Empty, "Value", "Text"), "- Seleccione el puesto -", new { @class = "lista resultado", @name = "SucursalID" })

                    <h4 class="Indicacion">Modulo:</h4>
                    @*@Html.DropDownList("ModuloID", new SelectList(string.Empty, "Value", "Text"), "- Seleccione el modulo -", new { @class = "lista resultado", @name = "SucursalID" })*@
                    <select id="ModuloID" multiple="multiple" style="display:none"></select>

                </div>
                <div class="modal-footer">
                    <button class="cnc" type="button" id="Cancelar" value="Cancelar" data-dismiss="modal" aria-label="Close" style="padding:5px 10px 1px!important;">
                        Cancelar
                    </button>
                    <button class="ok" type="button" id="AltaAcceso" value="Alta"> Guardar </button>
                </div>
            </form>
        </div>
    </div>
</div>
<script>
    //abrir modal de alta
    $("#AddAcceso").click(function () {
        $('#ShowAlta').modal('show');
        //Modulo
        $.ajax({
            type: 'POST',
            url: '@Url.Action("RolPermiso", "Permisos")',
            dataType: 'json',
            success: function (Response) {
               

                $.each(Response.Rol, function (i, Rol) {
                    $("#PuestoID").append('<option value="' + Rol.PermisoID + '">' + Rol.Modulo + '</option>');
                });
                //$.each(Response.Modulo, function (i, Modulo) {
                //    $("#ModuloID").append('<option value="' + Modulo.PermisoID + '">' + Modulo.Modulo + '</option>');
                //});
                $.each(Response.Modulo, function (i, Modulo) {
                    cuerpo = '<option value="' + Modulo.PermisoID + '">' + Modulo.Modulo + '</option>';
                    $("#ModuloID").append(cuerpo);
                });
                
                $('#ModuloID').multiselect({
                    includeSelectAllOption: false
                });

                              
            },
        });
    })

    //FUNCION ALTA NUEVO PERMISO
    $("#AltaAcceso").click(function () {

        var combo = document.getElementById("PuestoID");
        var RolID  = combo.options[combo.selectedIndex].value;

        var ModuloLista = $("#ModuloID option:selected");
        var Modulo = "";

        ModuloLista.each(function () {
            //Producto += $(this).text() + " " + $(this).val() + "\n";
            Modulo += $(this).val() + ",";
        });

        //Modulo
        $.ajax({
            type: 'POST',
            url: '@Url.Action("AddAccess", "Permisos")',
            dataType: 'json',
            data: { RolID, Modulo },
            success: function (Response) {
                $('#mensajeModal').modal('show');
                $('#resultado').html(Response);
                //alert(Response);

            },
        });

    })
</script>

<div class="modal fade" id="ShowModificar" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title Indicacion" id="staticBackdropLabel">Nuevo permiso por puesto</h4>
            </div>
            <form id="FormProducto">
                <div class="modal-body">
                    <h4 class="Indicacion">Puesto:</h4>
                    <input class="col-md-12" id="txt1" name="txt1" type="text" readonly />
                    <input class="col-md-12" id="cvePuesto" name="txt1" type="hidden" />
                    @*<select id="ModuloIDRes" multiple="multiple" style="display:none" class="lista resultado"></select>*@
                             
                </div>
                <div class="modal-footer">
                    <button class="cnc" type="button" id="Cancelar" value="Cancelar" data-dismiss="modal" aria-label="Close" style="padding:5px 10px 1px!important;">
                        Cancelar
                    </button>
                    <button class="ok" type="button" id="Eliminar" value="Eliminar"> Eliminar </button>
                </div>
            </form>
        </div>
    </div>
</div>

<style>
    .btn-group.open {
        width: 100% !important;
    }

    button.dropdown-item.multiselect-all {
        width: 100% !important;
        text-align: left !important;
    }

    button.multiselect-option.dropdown-item {
        width: 100% !important;
        text-align: left !important;
        background: white !important;
    }

        button.multiselect-option.dropdown-item:hover {
            width: 100% !important;
            text-align: left !important;
            background: #cacaca !important;
        }

    button.multiselect.dropdown-toggle.custom-select {
        width: 100% !important;
        text-align: left !important;
        background: white !important;
        font-size: 14px !important;
    }

    .btn-group {
        width: 100% !important;
        border: 1px solid #cacaca !important;
    }

    .multiselect-container.dropdown-menu {
        height: 350px !important;
        overflow: scroll !important;
    }
</style>

@*Mensaje al guardar la cantidad de dia habil*@
<div class="modal fade" id="mensajeModal" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close" onclick="location.reload();">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div id="resultado" class="text-center"></div>
                <button class="cnc" onclick="location.reload();" type="button">  Cerrar. </button>
            </div>

        </div>
    </div>
</div>
<script>
    //ELiminar pemriso
    $("#Eliminar").click(function () {
        var CodigoAlterno = $("#txt1").val();
        var Em_Puesto = $("#cvePuesto").val();


        $.ajax({
            type: 'POST',
            url: '@Url.Action("DeletePermisoLog", "Permisos")',
            dataType: 'json',
            data: { CodigoAlterno, Em_Puesto },
            success: function (Response) {
                $('#ShowModificar').modal('hide');
                $('#mensajeModal').modal('show');
                $('#resultado').html(Response);


            },
        });

    })
</script>

SistemaBase/Views/Permisos/gridControlIndOperacion.cshtml
@model IEnumerable<ENTIDADES.Seguridad.PermisoEmpleadoViewModel>
@using GridMvc.Html

@Html.Grid(Model).Columns(columns =>
            {
                columns.Add(c => c.Sucursal).Titled("Sucursal").Css("gridCel").Sortable(true).Filterable(false).Title.Trim();
                //columns.Add(c => c.Usuario).Titled("Usuario").Css("gridCel").Sortable(true).Filterable(true).Title.Trim();
                //columns.Add(c => c.FechaVar).Titled("Fecha").Css("gridCel").Sortable(true).Filterable(true);
                columns.Add(c => c.visitas).Titled("Visitas").Css("gridCel").Sortable(true).Filterable(false);
                columns.Add(c => c.comentarios).Titled("Comentarios").Css("gridCel").Sortable(true).Filterable(false);
            }).Sortable(true).EmptyText("Sin Registros")