SistemaBase/Controllers/RH/EntradasController.cs
using SistemaBase.Filters;

using SpreadsheetLight;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace SistemaBase.Controllers.RH
{
    public class EntradasController : Controller
    {

        // GET: Entradas
       // [AutorizarSession(idOperacion: (int)PuestoPermiso.permiso.ListTicketAsignado)]
        public ActionResult Index()
        {
            return View();
        }
         
        //[DeleteFileAttribute]
        //[HttpPost]
        //public async Task<FileResult> Index(EntradaViewModel entrada)
        //{
        //    Check = new CheckServicio();

        //    List<Entrada> entradasEmpobj = new List<Entrada>();
        //    Task<List<Entrada>> entradasEmp = Check.consultarEntradas(entrada);
        //    List<Entrada> entradaReal = await entradasEmp;

        //    string filename = System.IO.Path.GetTempPath() + "entradas.xls";
        //    SLDocument oSLDocument = new SLDocument();
        //    DataTable dt = new DataTable();

        //    dt.Columns.Add("fecha", typeof(String));
        //    dt.Columns.Add("dia", typeof(String));
        //    dt.Columns.Add("Suc Registro", typeof(String));
        //    dt.Columns.Add("Nombre", typeof(String));
        //    dt.Columns.Add("Suc Emp", typeof(String));
        //    dt.Columns.Add("Area", typeof(String));
        //    dt.Columns.Add("ENT", typeof(String));
        //    dt.Columns.Add("SAL", typeof(String));   
        //    dt.Columns.Add("ENT2", typeof(String));
        //    dt.Columns.Add("SAL2", typeof(String));
        //    dt.Columns.Add("ENT3", typeof(String));
        //    dt.Columns.Add("SAL3", typeof(String));

        //    // registros
        //    foreach (var item in entradaReal)
        //    {
        //        dt.Rows.Add( item.fecha, item.dia, item.SucChk, item.nombre, item.EmpSuc, item.EmpDep, item.ENT, item.SAL,
        //                    item.ENT2, item.SAL2, item.ENT3, item.SAL3);

        //    }
        

        //    oSLDocument.ImportDataTable(1, 1, dt, true);
        //    oSLDocument.SaveAs(filename);
        //    return File( filename,"application/xls","Entradas"+ entrada.fechaInicio +"--"+ entrada.fechaFin+ ".xls");
        //}
    }
}

SistemaBase/Views/Entradas/Index.cshtml
@model ENTIDADES.Check.EntradaViewModel
@{
    ViewBag.Title = "dwedc";
}


<section class="content-header">
    <h2>Index</h2>
    
</section>



      <!-- quick email widget -->
<div class="content">
    <div class="box box-info">
        <div class="box-header">
            <i class="fa fa-envelope"></i>

            <h3 class="box-title">Quick Email</h3>
            <!-- tools box -->
            @*<div class="pull-right box-tools">
                <button type="button" class="btn btn-info btn-sm" data-widget="remove" data-toggle="tooltip"
                        title="Remove">
                    <i class="fa fa-times"></i>
                </button>
            </div>*@
            <!-- /. tools -->
        </div>
        <div class="box-body">  
       

                @using (Html.BeginForm("Index", "Entradas", FormMethod.Post, new { @class = "form-horizontal" }))
                {

                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-2 control-label">Fecha Inicio</label>
                        <div class="col-sm-6">
                            <input type="date" class="form-control" name="fechaInicio" placeholder="Fecha inicio">
                        </div>
                    </div>


                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-2 control-label">Fecha Fin</label>
                        <div class="col-sm-6">
                            <input type="date" class="form-control" name="fechaFin" placeholder="Fecha inicio">
                        </div>
                    </div>

                    <div class="box-footer clearfix">
                        <button type="submit" class="pull-right btn btn-default" id="sendEmail">
                            Descargar
                            <i class="fa fa-arrow-circle-right"></i>
                        </button>
                    </div>

                }

         
        </div>
      
    </div>
</div>